name: flux
description: "Flux"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get_it: ^9.2.0
  shared_preferences: ^2.5.4
  dio: ^5.9.1
  flutter_lints: ^6.0.0
  flutter_quill: ^11.5.0
  path_provider: ^2.1.0
  flutter_localizations:
    sdk: flutter
  flutter_staggered_grid_view: ^0.7.0
  sqflite: ^2.4.2
  flutter_bloc: ^9.1.1
  intl: ^0.20.2
  google_generative_ai: ^0.4.7
  connectivity_plus: ^7.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/icons/
    - assets/images/
